name: MagicEyes

on:
  push:
    branches:
      - "*"
    paths:
      - '.github/workflows/MagicEyes.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - '.github/workflows/MagicEyes.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.CICD_PRIVATE_KEY }}
          SSH-agent: ssh-agent
      - name: Start SSH agent
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$CICD_PRIVATE_KEY")     

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and Init Env
        run: |
          sudo apt update
          sudo apt install libbpf-dev clang-14 llvm-14 libelf-dev libpcap-dev gcc-multilib build-essential cmake
          git submodule update --init --recursive

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DBUILD_ALL=ON ..
          make
